import type { BetInterface, IStake } from '@/src/lib/types';
import type { Address } from 'viem';
declare const useBets: (count: number) => import("@tanstack/react-query").UseQueryResult<BetInterface[], Error>;
declare const useAllStakes: (count: number) => import("@tanstack/react-query").UseQueryResult<IStake[], Error>;
declare const usePlayerBets: (count: number) => import("@tanstack/react-query").UseQueryResult<BetInterface[], Error>;
declare const useOpenProfile: () => {
    open: (address: Address) => void;
    close: () => void;
    data: {
        open: boolean;
        address: `0x${string}` | undefined;
    };
    error: Error;
    isError: true;
    isPending: false;
    isLoading: false;
    isLoadingError: false;
    isRefetchError: true;
    isSuccess: false;
    isPlaceholderData: false;
    status: "error";
    dataUpdatedAt: number;
    errorUpdatedAt: number;
    failureCount: number;
    failureReason: Error | null;
    errorUpdateCount: number;
    isFetched: boolean;
    isFetchedAfterMount: boolean;
    isFetching: boolean;
    isInitialLoading: boolean;
    isPaused: boolean;
    isRefetching: boolean;
    isStale: boolean;
    refetch: (options?: import("@tanstack/query-core").RefetchOptions) => Promise<import("@tanstack/query-core").QueryObserverResult<{
        open: boolean;
        address: `0x${string}` | undefined;
    }, Error>>;
    fetchStatus: import("@tanstack/query-core").FetchStatus;
    promise: Promise<{
        open: boolean;
        address: `0x${string}` | undefined;
    }>;
} | {
    open: (address: Address) => void;
    close: () => void;
    data: {
        open: boolean;
        address: `0x${string}` | undefined;
    };
    error: null;
    isError: false;
    isPending: false;
    isLoading: false;
    isLoadingError: false;
    isRefetchError: false;
    isSuccess: true;
    isPlaceholderData: false;
    status: "success";
    dataUpdatedAt: number;
    errorUpdatedAt: number;
    failureCount: number;
    failureReason: Error | null;
    errorUpdateCount: number;
    isFetched: boolean;
    isFetchedAfterMount: boolean;
    isFetching: boolean;
    isInitialLoading: boolean;
    isPaused: boolean;
    isRefetching: boolean;
    isStale: boolean;
    refetch: (options?: import("@tanstack/query-core").RefetchOptions) => Promise<import("@tanstack/query-core").QueryObserverResult<{
        open: boolean;
        address: `0x${string}` | undefined;
    }, Error>>;
    fetchStatus: import("@tanstack/query-core").FetchStatus;
    promise: Promise<{
        open: boolean;
        address: `0x${string}` | undefined;
    }>;
};
declare const useSide: (parent: Address, member: Address) => import("@tanstack/react-query").UseQueryResult<import("@/src/lib/types").TSide, Error>;
export declare const useRegistrationDate: (address: Address) => import("@tanstack/react-query").UseQueryResult<number, Error>;
export declare const useSidebar: () => {
    toggle: (state: boolean) => void;
    data: boolean;
    error: Error;
    isError: true;
    isPending: false;
    isLoading: false;
    isLoadingError: false;
    isRefetchError: true;
    isSuccess: false;
    isPlaceholderData: false;
    status: "error";
    dataUpdatedAt: number;
    errorUpdatedAt: number;
    failureCount: number;
    failureReason: Error | null;
    errorUpdateCount: number;
    isFetched: boolean;
    isFetchedAfterMount: boolean;
    isFetching: boolean;
    isInitialLoading: boolean;
    isPaused: boolean;
    isRefetching: boolean;
    isStale: boolean;
    refetch: (options?: import("@tanstack/query-core").RefetchOptions) => Promise<import("@tanstack/query-core").QueryObserverResult<boolean, Error>>;
    fetchStatus: import("@tanstack/query-core").FetchStatus;
    promise: Promise<boolean>;
} | {
    toggle: (state: boolean) => void;
    data: boolean;
    error: null;
    isError: false;
    isPending: false;
    isLoading: false;
    isLoadingError: false;
    isRefetchError: false;
    isSuccess: true;
    isPlaceholderData: false;
    status: "success";
    dataUpdatedAt: number;
    errorUpdatedAt: number;
    failureCount: number;
    failureReason: Error | null;
    errorUpdateCount: number;
    isFetched: boolean;
    isFetchedAfterMount: boolean;
    isFetching: boolean;
    isInitialLoading: boolean;
    isPaused: boolean;
    isRefetching: boolean;
    isStale: boolean;
    refetch: (options?: import("@tanstack/query-core").RefetchOptions) => Promise<import("@tanstack/query-core").QueryObserverResult<boolean, Error>>;
    fetchStatus: import("@tanstack/query-core").FetchStatus;
    promise: Promise<boolean>;
} | {
    toggle: (state: boolean) => void;
    data: undefined;
    error: Error;
    isError: true;
    isPending: false;
    isLoading: false;
    isLoadingError: true;
    isRefetchError: false;
    isSuccess: false;
    isPlaceholderData: false;
    status: "error";
    dataUpdatedAt: number;
    errorUpdatedAt: number;
    failureCount: number;
    failureReason: Error | null;
    errorUpdateCount: number;
    isFetched: boolean;
    isFetchedAfterMount: boolean;
    isFetching: boolean;
    isInitialLoading: boolean;
    isPaused: boolean;
    isRefetching: boolean;
    isStale: boolean;
    refetch: (options?: import("@tanstack/query-core").RefetchOptions) => Promise<import("@tanstack/query-core").QueryObserverResult<boolean, Error>>;
    fetchStatus: import("@tanstack/query-core").FetchStatus;
    promise: Promise<boolean>;
} | {
    toggle: (state: boolean) => void;
    data: undefined;
    error: null;
    isError: false;
    isPending: true;
    isLoading: true;
    isLoadingError: false;
    isRefetchError: false;
    isSuccess: false;
    isPlaceholderData: false;
    status: "pending";
    dataUpdatedAt: number;
    errorUpdatedAt: number;
    failureCount: number;
    failureReason: Error | null;
    errorUpdateCount: number;
    isFetched: boolean;
    isFetchedAfterMount: boolean;
    isFetching: boolean;
    isInitialLoading: boolean;
    isPaused: boolean;
    isRefetching: boolean;
    isStale: boolean;
    refetch: (options?: import("@tanstack/query-core").RefetchOptions) => Promise<import("@tanstack/query-core").QueryObserverResult<boolean, Error>>;
    fetchStatus: import("@tanstack/query-core").FetchStatus;
    promise: Promise<boolean>;
} | {
    toggle: (state: boolean) => void;
    data: undefined;
    error: null;
    isError: false;
    isPending: true;
    isLoadingError: false;
    isRefetchError: false;
    isSuccess: false;
    isPlaceholderData: false;
    status: "pending";
    dataUpdatedAt: number;
    errorUpdatedAt: number;
    failureCount: number;
    failureReason: Error | null;
    errorUpdateCount: number;
    isFetched: boolean;
    isFetchedAfterMount: boolean;
    isFetching: boolean;
    isLoading: boolean;
    isInitialLoading: boolean;
    isPaused: boolean;
    isRefetching: boolean;
    isStale: boolean;
    refetch: (options?: import("@tanstack/query-core").RefetchOptions) => Promise<import("@tanstack/query-core").QueryObserverResult<boolean, Error>>;
    fetchStatus: import("@tanstack/query-core").FetchStatus;
    promise: Promise<boolean>;
} | {
    toggle: (state: boolean) => void;
    data: boolean;
    isError: false;
    error: null;
    isPending: false;
    isLoading: false;
    isLoadingError: false;
    isRefetchError: false;
    isSuccess: true;
    isPlaceholderData: true;
    status: "success";
    dataUpdatedAt: number;
    errorUpdatedAt: number;
    failureCount: number;
    failureReason: Error | null;
    errorUpdateCount: number;
    isFetched: boolean;
    isFetchedAfterMount: boolean;
    isFetching: boolean;
    isInitialLoading: boolean;
    isPaused: boolean;
    isRefetching: boolean;
    isStale: boolean;
    refetch: (options?: import("@tanstack/query-core").RefetchOptions) => Promise<import("@tanstack/query-core").QueryObserverResult<boolean, Error>>;
    fetchStatus: import("@tanstack/query-core").FetchStatus;
    promise: Promise<boolean>;
};
export { useBets, usePlayerBets, useAllStakes, useOpenProfile, useSide };
