import { type PathFragmentFragment } from '@/.graphclient';
import { type LinearData, type TSide, type TreeMember } from '@/src/lib/types';
import type { Address } from 'viem';
export declare const fetchTreeMember: (member: Address) => Promise<TreeMember>;
export declare const findLastLeftMember: (member: Address) => Promise<Address>;
export declare const fetchMemberSide: (parent?: Address, member?: Address) => Promise<TSide>;
export declare const getSide: (parent: string, member: string) => TSide;
export declare const fetchPassByMemberAddress: (member?: Address) => Promise<bigint>;
export declare const fetchLinearData: (member: Address) => Promise<LinearData | null>;
export declare const mapLinearDataPath: (path: PathFragmentFragment[]) => LinearData["path"];
export declare const fetchMemberLinearStructure: (member: Address) => Promise<TreeMember | null>;
