/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as GamesIndexImport } from './routes/games/index'
import { Route as GamesLiveRouletteImport } from './routes/games/live-roulette'
import { Route as GamesRouletteIndexImport } from './routes/games/roulette/index'
import { Route as GamesRouletteSingleIndexImport } from './routes/games/roulette/single/index'
import { Route as GamesRouletteLiveTableImport } from './routes/games/roulette/live/$table'

// Create/Update Routes

const GamesIndexRoute = GamesIndexImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRoute,
} as any)

const GamesLiveRouletteRoute = GamesLiveRouletteImport.update({
  id: '/games/live-roulette',
  path: '/games/live-roulette',
  getParentRoute: () => rootRoute,
} as any)

const GamesRouletteIndexRoute = GamesRouletteIndexImport.update({
  id: '/games/roulette/',
  path: '/games/roulette/',
  getParentRoute: () => rootRoute,
} as any)

const GamesRouletteSingleIndexRoute = GamesRouletteSingleIndexImport.update({
  id: '/games/roulette/single/',
  path: '/games/roulette/single/',
  getParentRoute: () => rootRoute,
} as any)

const GamesRouletteLiveTableRoute = GamesRouletteLiveTableImport.update({
  id: '/games/roulette/live/$table',
  path: '/games/roulette/live/$table',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/games/live-roulette': {
      id: '/games/live-roulette'
      path: '/games/live-roulette'
      fullPath: '/games/live-roulette'
      preLoaderRoute: typeof GamesLiveRouletteImport
      parentRoute: typeof rootRoute
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesIndexImport
      parentRoute: typeof rootRoute
    }
    '/games/roulette/': {
      id: '/games/roulette/'
      path: '/games/roulette'
      fullPath: '/games/roulette'
      preLoaderRoute: typeof GamesRouletteIndexImport
      parentRoute: typeof rootRoute
    }
    '/games/roulette/live/$table': {
      id: '/games/roulette/live/$table'
      path: '/games/roulette/live/$table'
      fullPath: '/games/roulette/live/$table'
      preLoaderRoute: typeof GamesRouletteLiveTableImport
      parentRoute: typeof rootRoute
    }
    '/games/roulette/single/': {
      id: '/games/roulette/single/'
      path: '/games/roulette/single'
      fullPath: '/games/roulette/single'
      preLoaderRoute: typeof GamesRouletteSingleIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/games/live-roulette': typeof GamesLiveRouletteRoute
  '/games': typeof GamesIndexRoute
  '/games/roulette': typeof GamesRouletteIndexRoute
  '/games/roulette/live/$table': typeof GamesRouletteLiveTableRoute
  '/games/roulette/single': typeof GamesRouletteSingleIndexRoute
}

export interface FileRoutesByTo {
  '/games/live-roulette': typeof GamesLiveRouletteRoute
  '/games': typeof GamesIndexRoute
  '/games/roulette': typeof GamesRouletteIndexRoute
  '/games/roulette/live/$table': typeof GamesRouletteLiveTableRoute
  '/games/roulette/single': typeof GamesRouletteSingleIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/games/live-roulette': typeof GamesLiveRouletteRoute
  '/games/': typeof GamesIndexRoute
  '/games/roulette/': typeof GamesRouletteIndexRoute
  '/games/roulette/live/$table': typeof GamesRouletteLiveTableRoute
  '/games/roulette/single/': typeof GamesRouletteSingleIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/games/live-roulette'
    | '/games'
    | '/games/roulette'
    | '/games/roulette/live/$table'
    | '/games/roulette/single'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/games/live-roulette'
    | '/games'
    | '/games/roulette'
    | '/games/roulette/live/$table'
    | '/games/roulette/single'
  id:
    | '__root__'
    | '/games/live-roulette'
    | '/games/'
    | '/games/roulette/'
    | '/games/roulette/live/$table'
    | '/games/roulette/single/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  GamesLiveRouletteRoute: typeof GamesLiveRouletteRoute
  GamesIndexRoute: typeof GamesIndexRoute
  GamesRouletteIndexRoute: typeof GamesRouletteIndexRoute
  GamesRouletteLiveTableRoute: typeof GamesRouletteLiveTableRoute
  GamesRouletteSingleIndexRoute: typeof GamesRouletteSingleIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  GamesLiveRouletteRoute: GamesLiveRouletteRoute,
  GamesIndexRoute: GamesIndexRoute,
  GamesRouletteIndexRoute: GamesRouletteIndexRoute,
  GamesRouletteLiveTableRoute: GamesRouletteLiveTableRoute,
  GamesRouletteSingleIndexRoute: GamesRouletteSingleIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/games/live-roulette",
        "/games/",
        "/games/roulette/",
        "/games/roulette/live/$table",
        "/games/roulette/single/"
      ]
    },
    "/games/live-roulette": {
      "filePath": "games/live-roulette.tsx"
    },
    "/games/": {
      "filePath": "games/index.tsx"
    },
    "/games/roulette/": {
      "filePath": "games/roulette/index.tsx"
    },
    "/games/roulette/live/$table": {
      "filePath": "games/roulette/live/$table.tsx"
    },
    "/games/roulette/single/": {
      "filePath": "games/roulette/single/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
